db:
  build: .
  volumes:
    - ./initdb.d:/docker-entrypoint-initdb.d
    - ./mycnf:/etc/mysql/conf.d/
  environment:
    MYSQL_ROOT_PASSWORD: password
  command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --secure-file-priv="/docker-entrypoint-initdb.d"